[tool.poetry]
name = "hexlet-code"
version = "0.1.0"
description = "Task manager - This is a site that allows you to create and track tasks."
readme = "README.md"
requires-python = ">=3.12"
dependencies = []

[tool.poetry.group.dev.dependencies]
flake8 = "^7.1.1"
coverage = "^7.6.1"
